# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
