# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0004_auto_20180224_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_users',
            new_name='review_user',
        ),
    ]
