# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
    ]
